PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Client_Interview_Ready__c.field-meta.xml
<CustomField>
    <fullName>Client_Interview_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Interview Ready</label>
    <type>Checkbox</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>90</fullName>
                <default>true</default>
                <label>90</label>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Skype</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Overall_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Overall_Feedback__c</fullName>
    <label>Overall Feedback</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Panel_Comments__c.field-meta.xml
<CustomField>
    <fullName>Panel_Comments__c</fullName>
    <label>Panel Comments</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Panel_Round__c.field-meta.xml
<CustomField>
    <fullName>Panel_Round__c</fullName>
    <label>Panel Round</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Recording_Consent__c.field-meta.xml
<CustomField>
    <fullName>Recording_Consent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recording Consent</label>
    <type>Checkbox</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Recording_Link__c.field-meta.xml
<CustomField>
    <fullName>Recording_Link__c</fullName>
    <label>Recording Link</label>
    <type>Url</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Stability__c.field-meta.xml
<CustomField>
    <fullName>Stability__c</fullName>
    <label>Stability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Topics_to_be_Repaneled__c.field-meta.xml
<CustomField>
    <fullName>Topics_to_be_Repaneled__c</fullName>
    <label>Topics to be Repaneled</label>
    <summaryFilterItems>
        <field>Topic__c.Repanel__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Score__c</fullName>
    <label>Total Score</label>
    <summarizedField>Topic__c.Max_Score__c</summarizedField>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Training_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Training_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Assignment</label>
    <referenceTo>Training_Center__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Actual_Score__c.field-meta.xml
<CustomField>
    <fullName>Actual_Score__c</fullName>
    <label>Actual Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/fields/Repanel__c.field-meta.xml
<CustomField>
    <fullName>Repanel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repanel</label>
    <type>Checkbox</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Training_Center__c/Training_Center__c.object-meta.xml
<CustomObject>
    <label>Training Center</label>
    <nameField>
        <label>Training Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/classes/DetailedPanelResultsController.cls
public class DetailedPanelResultsController {
    @AuraEnabled
    public static Panel__c GetPanel(String Name){
        Panel__c getPanel = [SELECT Panel__c.Contact__r.Name, Panel__c.Assigned_To__r.Name, Date_Time__c, Duration__c, Mode__c, 
                             Client_Interview_Ready__c, Overall_Feedback__c, Panel_Comments__c, Placement__c, Panel_Round__c,
                             Recording_Consent__c, Recording_Link__c, Stability__c, Panel__c.Template__r.Name, Panel__c.Training_Assignment__r.Name, Max_Score__c, 
                             Total_Score__c, Topics_to_be_Repaneled__c FROM Panel__c WHERE Name =: Name LIMIT 1];
        
        return getPanel;
    }
    @AuraEnabled
    public static List<Topic__c> GetTopics(String Name){
        //integer count = 0;
        //integer Max_Score = 0;
        //integer final_score = 0;
        List<Topic__c> topics = [SELECT Name, Actual_Score__c, Comments__c, Max_Score__c, Repanel__c FROM Topic__c WHERE Panel__r.Name =: Name];
        /*for(Topic__c topic: Topics){
            if(topic.Repanel__c == true){
                count++;
            }
            Max_score += topic.Max_Score__c;
            final_score += topic.Actual_Score__c;
            
        }
        Topic__c lastTopic = new Topic__c();
        lastTopic.Name = 'Total';
        lastTopic.Max_Score__c = Max_score;
        lastTopic.Actual_Score__c = final_score;
        topics.add(lastTopic);*/
        
        return topics;
    }
}