PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Curriculum__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/classes/FilterPanelResultsByNameControllerTest.cls
@isTest
public class FilterPanelResultsByNameControllerTest{
    
    final static Integer NUMBER_OF_RECORDS = 2;
    
    @TestSetup
    private static void GenerateMockData(){
        
        List<Contact> contactList = new List<Contact>();
        List<Panel__c> panelList = new List<Panel__c>();
        
        //Mock Curriculum
        Curriculum__c curr = new Curriculum__c();
        curr.Name = 'Test Curriculum';
        curr.Topics__c = 'PostalForce,AuraForce,PanelForce';
        curr.Max_Scores__c = '5,10,15';
        insert curr;
        
        //Mock Contacts
        for (Integer i = 0; i < NUMBER_OF_RECORDS; i++){
            
            Contact con = new Contact();
            con.FirstName = 'Test Contact';
            con.LastName = String.valueOf(i);
            con.Phone = '(555) 555-555' + String.valueOf(i);
            con.Email = 'test.contact-' + String.valueOf(i) + '@test.com';
            contactList.add(con);
        }
        
        insert contactList;
        
        //Mock Panels
        for (Integer i = 0; i < NUMBER_OF_RECORDS; i++){
            
            Panel__c pan = new Panel__c();
            pan.Contact__c = contactList[i].Id;
            pan.Template__c = curr.Id;
            panelList.add(pan);
        }
        
        insert panelList;
    }
    
    @isTest
    public static void GetPanelsTest(){
        
        List<Panel__c> panelList = FilterPanelResultsByNameController.GetPanels();
        
        System.assertEquals(NUMBER_OF_RECORDS, panelList.size());
    }
    
    @isTest
    public static void GetContactPanelsTest(){
        
        List<Panel__c> panelList = FilterPanelResultsByNameController.GetContactPanels('Test Contact 0');
        
        System.assertEquals(1, panelList.size());
        System.assertEquals('Test Contact 0', panelList[0].Contact__r.Name);
    }
}