PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Curriculum__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/TestDetailedPanelResultsController.cls
@isTest
public class TestDetailedPanelResultsController {
    
    @testSetup
    static void setupPanelTest(){
        List<Panel__c> pans = new List<Panel__c>();
        List<Curriculum__c> currs = new List<Curriculum__c>();
        Contact con = new Contact(LastName = 'Rhee');
        insert con;

        for (Integer i = 0; i < 10; i++) {
            Curriculum__c curr = new Curriculum__c(Name = 'Temp');
            curr.Topics__c = 'Tech1,Tech2,Tech3,Tech4';
            curr.Max_Scores__c = '21,22,23,24';
            currs.add(curr);
            // currs.add(new Curriculum__c(Name = 'Temp', Topics__c = 'Tech1,Tech2,Tech3,Tech4', Max_Scores__c = '21,22,23,24'));
            
        }
        insert currs;

        for (Integer i = 0; i < 10; i++) {
            pans.add(new Panel__c(Template__c = currs[i].Id, Contact__c = con.Id));
            System.debug(currs[i]);
            System.debug(pans[i]);
        }
        insert pans;
    }
    
    @isTest
    public static void testGetPanel(){
        Panel__c randomPanel = [SELECT Name, Id FROM Panel__c LIMIT 1];
        String testId = randomPanel.Id;
        test.startTest();
        Panel__c checkPanel = DetailedPanelResultsController.GetPanel(testId);
        test.stopTest();
        System.assertEquals(testId, checkPanel.Id);
        
    }
    
    @isTest
    public static void testGetTopics(){
        Panel__c randomPanel = [SELECT Name, Id FROM Panel__c LIMIT 1];
        String testId = randomPanel.Id;
        List<Topic__c> testTopics = [SELECT Name, Max_Score__c FROM Topic__c WHERE Panel__r.Id =: testId];
        test.startTest();
        List<Topic__c> gottenTopics = DetailedPanelResultsController.GetTopics(testId);
        test.stopTest();
        System.assertEquals(testTopics.size(), gottenTopics.size());
        for(integer i = 0; i < testTopics.size(); i++){
            system.assertEquals(testTopics[i].Name, gottenTopics[i].Name);
            system.assertEquals(testTopics[i].Max_Score__c, gottenTopics[i].Max_Score__c);
        }
    }

}