PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Curriculum__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/TopicMakerTest.cls
@isTest
public class TopicMakerTest {
    @testSetup
    static void TestTopicMakerSetup(){
        List<Panel__c> pen = new List<Panel__c>();
        
        //[SELECT Id, Name, Contact__c, Template__r.Topics__c, Template__r.Max_Score__c FROM Panel__c];
        //Panel__c pen = new Panel__c(Name = '', );

        for (Integer i = 0; i < 10; i++){
            // contact__c con = new Contact__c(LastName = 'TestLastName' + i, FirstName = 'TestFirstName' + i);
            Curriculum__c temp = new Curriculum__c(Name = 'Temp' + i);
            temp.Topics__c = 'Tech1, Tech2, Tech3, Tech4';
            temp.Max_Scores__c = '20, 24, 16, 25';
            
            insert temp;
            Panel__c x  = new Panel__c(Template__r = temp);
            pen.add(x);
        }
        insert pen;
        
   
    }

    @isTest
    static void testTopicMaker() {
        Panel__c ivan = new Panel__c();
        List<Panel__c> panelList = [SELECT Id, Name FROM Panel__c];
        Curriculum__c temp  = [SELECT Name, Max_Scores__c, Topics__c FROM Curriculum__c WHERE Name = 'Temp 1' LIMIT 1];
        // Topic__c top = [SELECT Name, Max_Score__c, Panel__c FROM Topic__c WHERE ];
        System.assertEquals('Tech1', temp.Topics__c);  
        System.assertEquals('20', temp.Max_Scores__c);
            
        System.assertNotEquals(' ', temp.Topics__c);
        System.assertNotEquals(' ', temp.Max_Scores__c);

        // System.assertEquals( );
        

        
    
    }
}