PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Curriculum__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Actual_Score__c.field-meta.xml
<CustomField>
    <fullName>Actual_Score__c</fullName>
    <label>Actual Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/RecordPanelDataControllerTest.cls
@isTest
public class RecordPanelDataControllerTest {

    @TestSetup
    public static void testSetup(){
        
                
    }
    @isTest
    public static void testGetTopics(){
         test.startTest();
        //Create contacts to associate to panels
        Contact testContact = new Contact(LastName = 'Test Name');
        insert testContact;
        //create curriculums (templates) to associate to panels
        Curriculum__c testCurr = new Curriculum__c(Name = 'Test Curr', Max_Scores__c = '2,3', Topics__c = 'topic 2,topic3');
        insert testCurr;
        //Create a bunch of test panels.
        Panel__c testPanel = new Panel__c(Template__c = testCurr.Id, Contact__c = testContact.Id );
        insert testPanel;
        
        //
        List<Topic__c> listTopic = RecordPanelDataController.getTopics(testPanel.id);
        
        //New list of topics
        
        List<Topic__c> newTopicsList = listTopic;
        newTopicsList[0].Actual_Score__c = 100;
        Id topicId = newTopicsList[0].Id;
        newTopicsList[0].Comments__c = 'Comment';
        newTopicsList[1].Comments__c = 'Comment';
        
       
        RecordPanelDataController.updatePanelTopics(testPanel.id, newTopicsList );
        system.debug('Record panel test stuff' + newTopicsList);
        Panel__c newPanel = [Select id, (SELECT Actual_Score__c FROM Topics__r WHERE id = : topicId) FROM Panel__c WHERE id =: testPanel.Id];
        system.debug(newPanel);
        
        System.assert(listTopic.size() != 0);
        System.assertEquals(100,newPanel.Topics__r[0].Actual_Score__c);
        
        
        Test.stopTest();
            
        
       }//End testgetTopics
    
   
    
}