PanelForce/force-app/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curriculums</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Curriculum__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Curriculum__c/fields/Topics__c.field-meta.xml
<CustomField>
    <fullName>Topics__c</fullName>
    <label>Topics</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Scores__c.field-meta.xml
<CustomField>
    <fullName>Max_Scores__c</fullName>
    <label>Max Scores</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/TopicMaker.cls
public class TopicMaker {
    public static void createTopics(List<Panel__c> panels) {
        List<Topic__c> topics = new List<Topic__c>();
        for (Panel__c p: panels) {
            if (p.Template__c != null) {
                List<String> topicStr = p.Template__r.Topics__c.split(',');//= {'tech1','tech2','tech3','tech4'}
                List<String> maxScores = p.Template__r.Max_Scores__c.split(',');
                if(topics.size() != maxScores.size())
                    p.addError('CSV are not the same size');
                else 
                    for (Integer i = 0; i < topicStr.size(); i++) {
                        Topic__c topic = new Topic__c();//Creating a Topic object here
                        topic.Name = topicStr[i];
                        topic.Max_Score__c = Integer.valueOf(maxScores[i]);
                        topic.Panel__c = p.Id;
                        topics.add(topic);
                }
            }
        }
        if (topics.size() > 0)
            insert topics;
    }
}