PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/PanelHistoryController.cls
public class PanelHistoryController {
	@AuraEnabled
    public static List<Panel__c> GetContactPanels(string contactId){   
        /* Returns Panel__c Filtered by Contact Name */
        system.debug(contactId);
        id contactnumber = id.valueof(contactId);
        system.debug(contactnumber);
        List<Panel__c> panelList  = [SELECT Name, Panel__c.Contact__r.Name, id FROM Panel__c WHERE Contact__c =: contactnumber];
        system.debug('you enter this');
        return panelList;
    }
}