PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Panel_Round__c.field-meta.xml
<CustomField>
    <fullName>Panel_Round__c</fullName>
    <label>Panel Round</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/classes/PanelRoundHelper.cls
public class PanelRoundHelper {
    public static void incrementPanelRound(List<Panel__c> panels) {
        List<Id> contactIds = new List<Id>();
        for (Panel__c p: panels)
            contactIds.add(p.Contact__c);
        List<Contact> cons = [SELECT Id, (SELECT Id FROM Panels__r) FROM Contact WHERE Id IN :contactIds];
        for (Panel__c p: panels) {
            Contact con; Integer i = 0;
            while (con == null && i < cons.size()) {
                if (cons[i].Id == p.Contact__c)
                    con = cons[i];
                i++;
            }
            p.Panel_Round__c = con.Panels__r.size() + 1;
        }
    }
}