PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/classes/FilterPanelResultsByNameController.cls
public class FilterPanelResultsByNameController{
    
    @AuraEnabled
    public static List<Panel__c> GetPanels(){
        
        /* Returns All Panel__c in Org */
        List<Panel__c> panelList  = [SELECT Name, Panel__c.Contact__r.Name, Id FROM Panel__c];
        
        return panelList;
    }
    
    @AuraEnabled
    public static List<Panel__c> GetContactPanels(String contactName){
        
        String contactNameString = '%' + contactName + '%';
        String escapedContactNameString = String.escapeSingleQuotes(contactNameString);
        
        /* Returns Panel__c Filtered by Contact Name */
        List<Panel__c> panelList  = [SELECT Name, Panel__c.Contact__r.Name, Id FROM Panel__c WHERE Panel__c.Contact__r.Name LIKE :escapedContactNameString];
        
        return panelList;
    }
}