PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>Panel - {0}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Client_Interview_Ready__c.field-meta.xml
<CustomField>
    <fullName>Client_Interview_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client Interview Ready</label>
    <type>Checkbox</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_Time__c</fullName>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

PanelForce/force-app/main/default/objects/Panel__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <summaryForeignKey>Topic__c.Panel__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Overall_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Overall_Feedback__c</fullName>
    <label>Overall Feedback</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Panel_Comments__c.field-meta.xml
<CustomField>
    <fullName>Panel_Comments__c</fullName>
    <label>Panel Comments</label>
    <type>TextArea</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Panel__c/fields/Recording_Link__c.field-meta.xml
<CustomField>
    <fullName>Recording_Link__c</fullName>
    <label>Recording Link</label>
    <type>Url</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/Topic__c.object-meta.xml
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PanelForce/force-app/main/default/objects/Topic__c/fields/Actual_Score__c.field-meta.xml
<CustomField>
    <fullName>Actual_Score__c</fullName>
    <label>Actual Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <label>Max Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PanelForce/force-app/main/default/objects/Topic__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <label>Panel</label>
    <referenceTo>Panel__c</referenceTo>
    <relationshipLabel>Topics</relationshipLabel>
    <relationshipName>Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PanelForce/force-app/main/default/force-app/main/default/objects/Topic__c/fields/Repanel__c.field-meta.xml
<CustomField>
    <fullName>Repanel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repanel</label>
    <type>Checkbox</type>
</CustomField>

PanelForce/force-app/main/default/classes/RecordPanelDataController.cls
public class RecordPanelDataController{
    
    /* Retrieve the Topics related to the specific panel.
    Provide a unique panel object Id. Returns a list of related topics. */
    @auraEnabled
    public static List<Topic__c> getTopics(String panelID) {
        //Query for panel with child-query for related topics.
        Panel__c panel = [SELECT Id,(SELECT Id,Name,Actual_Score__c,Max_Score__c,Repanel__c FROM Topics__r) FROM Panel__c WHERE ID=:panelID];

        //System.Debug(panel.Topics__r);
        return panel.Topics__r;
    }

    
    /* Query for a specific panel. Accepts a panelId and list of topics. Returns nothing. 
    Updates the Topic object's fields related to the panel. */
    @AuraEnabled
    public static void updatePanelTopics(String panelId, List<Topic__c> topics, Panel__c panelObj){
        //Retrieve the one panel by using the provided panelId. 
        Panel__c panel = [SELECT Id,Date_Time__c,Client_Interview_Ready__c,Overall_Feedback__c,Panel_Comments__c,Recording_Link__c,
                                    (SELECT Id,Actual_Score__c,Repanel__c,Comments__c FROM Topics__r) FROM Panel__c WHERE ID=:panelId];
        
        
        
        
        DateTime NOW = datetime.now();
        
        DateTime LAST_HOUR = NOW.addHours(1);
        
        System.Debug('This is PanelObj: ' +panelObj + ' ' + NOW + ' ' + LAST_HOUR);
        
        //Store Topics related to retrieved panel object.
        List<Topic__c> oldTopics = panel.Topics__r;

        //Update each related topic.
        for(Integer i = 0;i<oldTopics.Size();i++){
            //field by field.
            for(Integer j =0;j<topics.Size();j++){
                if(topics[j].id==oldTopics[i].id){
                    oldTopics[i].Actual_Score__c = topics[j].Actual_Score__c;
                    oldTopics[i].Comments__c = topics[j].Comments__c;
                    oldTopics[i].Repanel__c = topics[j].Repanel__c;
                }
            }

        }
        
        panel.Client_Interview_Ready__c = panelObj.Client_Interview_Ready__c;
        panel.Overall_Feedback__c = panelObj.Overall_Feedback__c;
        panel.Panel_Comments__c = panelObj.Panel_Comments__c;
        panel.Recording_Link__c = panelObj.Recording_Link__c;
        panel.Date_Time__c = LAST_HOUR;

        System.Debug('old: ' + panel);
        
        update oldTopics;
        update panel;
        System.Debug('new: ' + panel);
        
        

    }

}